set(0, 'DefaultAxesBox', 'off',...
'DefaultFigureColor', 'White',...
'DefaultAxesFontSize', 20,...
'DefaultAxesFontName', 'Helvetica',...
'DefaultAxesFontWeight', 'Bold',...
'DefaultAxesLayer', 'Bottom', ...
'DefaultAxesUnits', 'normalized',...
'DefaultAxesXcolor', [.3 .3 .3], ...
'DefaultAxesYcolor', [.3 .3 .3], ...
'DefaultAxesZcolor', [.3 .3 .3], ...
'DefaultAxesVisible', 'on', ...
'DefaultAxesYGrid', 'on', ...
'DefaultAxesXGrid', 'on', ...
'DefaultLineLineStyle','-', ...
'DefaultAxesTickDir', 'out',...
'DefaultAxesXMinorTick', 'on',...
'DefaultAxesYMinorTick', 'on',...
'DefaultAxesTicklength', [.02 .02],...
'DefaultLineLineWidth', 1, ...
'DefaultLineMarker', 'none', ...
'DefaultLineMarkerSize', 5, ...
'DefaultTextFontSize',12, ...
'DefaultTextFontName', 'Helvetica',...
'DefaultTextVerticalAlignment', 'middle', ...
'DefaultTextHorizontalAlignment', 'left');
set(0,'defaultAxesLineWidth',1)